services:
    resource.game:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Game" ]
        tags:      [ { name: "api.resource" } ]

    resource.player:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Player" ]
        tags:      [ { name: "api.resource" } ]

    resource.move:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Move" ]
        tags:      [ { name: "api.resource" } ]

    create_event_listener:
        class: "AppBundle\EventListener\CreateEventListener"
        tags:  [ { name: "kernel.event_listener", event: "api.pre_create", method: "onPreCreate" } ]
